function [times, freqs, tf_data] = get_time_freq( data, tf )


tlimits = tf.tlimits;
frames = tf.frames;
winSize = tf.winSize;
srate = tf.srate;
freq_rng = tf.freq_rng;
cycles = tf.cycles;
detrend = tf.detrend;
baseline = tf.baseline;
basenorm = tf.basenorm;
plotersp = tf.plotersp;
plotitc = tf.plotitc;
plotphase = tf.plotphase;
padratio = tf.padratio;
scale = tf.scale;


[~, ~, ~, times, freqs, ~, ~, tf_data] = newtimef(data, ...
    frames, ...
    tlimits, ...
    srate, ...
    cycles, ...
    'detrend', detrend, ...
    'baseline', baseline', ...
    'winsize', winSize, ...
    'freqs', freq_rng, ...
    'basenorm', basenorm, ...
    'plotersp', plotersp, ...
    'plotitc', plotitc, ...
    'plotphase', plotphase, ...
    'padratio', padratio, ...
    'scale', scale );

tf_data = abs(tf_data.^2);
end